basePath: /
definitions:
  dto.AccessTokenResponse:
    properties:
      access_token:
        type: string
    type: object
  dto.HotelAdd:
    properties:
      location:
        maxLength: 400
        minLength: 2
        type: string
      title:
        maxLength: 100
        minLength: 2
        type: string
    required:
    - location
    - title
    type: object
  dto.StatusResponse:
    properties:
      status:
        example: OK
        type: string
    type: object
  dto.User:
    properties:
      email:
        type: string
      id:
        type: integer
    type: object
  dto.UserRequestAdd:
    properties:
      email:
        type: string
      password:
        maxLength: 72
        minLength: 2
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: Booking service API
  title: Booking API
  version: "1.0"
paths:
  /auth/login:
    post:
      description: Returns JWT token
      parameters:
      - description: Registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UserRequestAdd'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AccessTokenResponse'
      tags:
      - auth
  /auth/logout:
    post:
      description: Logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.StatusResponse'
      tags:
      - auth
  /auth/me:
    get:
      description: Returns User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.User'
      tags:
      - auth
  /auth/register:
    post:
      description: Add User with hashed password
      parameters:
      - description: Registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UserRequestAdd'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.StatusResponse'
      tags:
      - auth
  /hotels/:
    post:
      description: Add Hotel
      parameters:
      - description: Registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.HotelAdd'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.StatusResponse'
      tags:
      - hotels
swagger: "2.0"
